### ISSUE TITLE
ASN Bank Zakelijk

### ISSUE THREAD

**Issue by DohnJoe1** [PrivSec-dev/banking-apps-compat-report#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

ASN Bank Zakelijk

### Link to app

https://play.google.com/store/apps/details?id=nl.asnbank.asnbankieren

### App version

2.40.2

### Country of the app

Netherlands

### Build Number

SQ3A.220705.003.A1.2022071100

### Device

- [X] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [x] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Ontill this moment, i did not find anything that did not worked. It seems that the app works like on stock OS

### Are there any extra notes you think users should know about?

nope

**Comment by aerique** [comment]
Also works on Pixel 6 Pro without Google Play and Google Play Services installed.

**Comment by aerique** [comment]
> Tried with one of my customers but you cannot log in to the app without Google Play Services @aerique Please correct this @akc3n

No, do not correct anything yet. Lets first figure out which app we're talking about.

I'm using the top app which is the generic banking app. It's updated, I can login, I can scan QR codes and pay. I use it almost every day, sometimes multiple times. I also do not have Google apps installed, not even in GrapheneOS' sandbox.
![Screenshot_20220829-155749](https://user-images.githubusercontent.com/89097/187222792-e32729df-18b1-4b9c-b2e1-c983e5c08fc5.png)
![Screenshot_20220829-155843](https://user-images.githubusercontent.com/89097/187222918-74690f55-2dae-4447-8cdb-a54d9e1ec71b.png)

**Comment by akc3n** [comment]
If anyone is still experiencing compatibility issues with this banking app, please read new pinned issue post here:
https://github.com/PrivSec-dev/banking-apps-compat-report/issues/170

**Comment by akc3n** [comment]
@DohnJoe1 The link to [app you provided is from a search result](https://play.google.com/store/search?q=asn%20bank&c=apps&hl=nl&gl=US), listing several apps. Could you please correct your initial report to specifically include the exact app you were referring to.

I.E., The link to app you provided is incorrect:
`https://play.google.com/store/search?q=asn%20bank&c=apps&hl=nl&gl=US`

The correct url would look like this:
`https://play.google.com/store/apps/details?id=nl.devolksbank.asn.bankieren`

**Comment by DohnJoe1** [comment]
Edited

**Comment by akc3n** [comment]
> Edited

Thank you @DohnJoe1

**Comment by aerique** [comment]
I'll go factory reset my spare GrapheneOS phone and see if @ph00lt0 is correct, because this was never the case in the past. (But now I'm afraid to wipe it from my main phone and not being able to install it ;-) )

**Comment by aerique** [comment]
I just did a factory reset on my Pixel 4a with GrapheneOS.

Looking in Apps there's "GmsCompat config" installed which I had not noticed before. Besides that Google Play Store, Google Play services and Google Services Framework are not installed.

After downloading F-Droid, installing Aurora and then installing ASN Mobiel Bankieren I was able to set it up and use it with any issues. For setting it up I used my "digipas" (the little red device) and skipped fingerprint setup.

**Comment by akc3n** [comment]
> installing ASN Mobiel Bankieren I was able to set it up and use it with any issues.

@aerique that's great, I'm glad that its working for you! Grateful to you for taking initiative, troubleshooting and volunteering your time. Appreciate you sharing the steps for resolving the matter.

**Comment by akc3n** [comment]
@ph00lt0 Thank you for being proactive and helping out. That's very kind of you.
> Sorry but none of this was relevant @akc3n. 

I understand and would appreciate any suggestions for emphasizing the purpose of my post:
> **Banking app issues:**
> How to potentially resolve banking app compatibility issues

Hopefully this can help others understand the simplicity of this linked post referencing in my intro to read our updated guides and highlighting possible 2 solutions related from our detailed guides on banking apps as well as compatibility layer.

**Comment by Sensor66** [comment]
The link under [ASN Bank](https://play.google.com/store/search?q=asn%20bank&c=apps&hl=nl&gl=US)  is confusing: because it is a search and leads to both the ASN Banking app (which is the one we are talking about) , and the beta channel Banking app , and the ASN *Payment* app, which are NOT what is meant.

Please correct that link to   https://play.google.com/store/apps/details?id=nl.asnbank.asnbankieren

Anyway, I can confirm that the Banking app works perfectly on Pixel 6a.  The other two apps I have not tested.

**Comment by Stephan-P** [comment]
@akc3n, there's confusion here.
1. This item is listed as ASN Mobiel Betalen in the banking apps list
2. The ASN Mobiel Betalen app (for NFC payments) has been taken out of order in March 2024 and thus should be removed from the list
3. ASN Bank no longer offers a proprietary app for contactless payments via NFC, for which one is supposed to use Google Pay :-(
4. On january 6, this Github Issue was renamed  into ASN Bank Zakelijk, which is (was)  a different app altogether
5. ASN Bank Zakelijk (for business accounts) has been taken offline since april 2024
6. At present ASN Bank in the Netherlands offers one unified app "ASN Bank" for personal and business accounts and this app does not support NFC contactless payments

**Comment by Stephan-P** [comment]
BTW, the same remarks are applicable to 
- Regio Bank Mobiel betalen
- SNS Mobiel betalen

**Comment by Stephan-P** [comment]
This listing on https://privsec.dev/posts/android/banking-applications-compatibility-with-grapheneos/#netherlands is outdated as per info provided above
![image](https://github.com/PrivSec-dev/banking-apps-compat-report/assets/10008599/23a7b1a0-d309-4d97-a59b-30cc128a7096)

**Comment by Stephan-P** [comment]
I landed here after following the Report link

**Comment by spring-onion** [comment]
@ph00lt0 @Stephan-P I was about to ask if someone could shed some light on what is going on in this mess when I saw you two had conveniently already laid it out. Thank you very much for the help, this has been a big thorn in my eye.

So this would be the new list:

ABN AMRO
ASN Bank
ING Bankieren
Rabobank
RegioBank
SNS
Triodos Bankieren NL

It looks like the original report here pertained to the business app that no longer exists (that's where the name change came from). Can we just drop in replace the dead play store link with this one? https://play.google.com/store/apps/details?id=nl.devolksbank.asn.bankieren

Also these two entries:

Regio Bank
SNS

also point to the issue here. Judging by #299 they're both owned by ASN Bank and these apps are just copies of the original with a diferent coat of paint right? We typically use one issue per app so it remains to be seen how we end up dealing with this.

**Comment by Stephan-P** [comment]
Volksbank is the parent company of ASN, RegioBank and SNS. (https://www.devolksbank.nl/en/)
One cannot open an account at Volksbank and hence there are no Volksbank apps available.

The apps for ASN Bank, SNS Bank and RegioBank are all development at/by the parent company Volksbank. 
All three have gone through the same changes these past few months. 
As such one can safely say that all share the same features or non-features. Hence my summary.
So YES, the apps for these banks are "replica's" with different branding:

- ASN Bank
- SNS Bank
- RegioBank

**Comment by Stephan-P** [comment]
Now, if they're all functional, or just one for that matter, I cannot state at this point.
I do not have a GOS device as of yet. I intend to buy one soon and then I'll be able to tell you how I've been fairing with the ASN Bank. Given the recent developments of the app, as well as some communications I have had with their support, I am not too sure if the ASN Bank will somehow function on GOS. At least they claim NOT TO SUPPORT anything that is not standard Android.  If that will turn out to be the case, then I need to think really hard about continuing with GOS (without banking app) or reverting to standard Pixel Android (with).

**Comment by Stephan-P** [comment]
possibly one of the other respondents in this thread can tell if the latest versions of ASN Bank, SNS Bank or RegioBank function with the latest GOS.

**Comment by Sensor66** [comment]
The ASN Bank app works, and has always worked. I use it both  on Graphene OS and on eOS.
I don't know about Mobile payments, I don't use that.

**Comment by spring-onion** [comment]
> These 3 should be listed one app per bank.

Yes I agree. If someone here uses either SNS or Regiobank, feel free to put up a new issue so we can split them up.

**Comment by fckff** [comment]
> Alright. And it's all functional? Aside from NFC payments, since they moved over to Google Pay.

For me and for at least one other person that I know, scanning of QR codes stopped working (coincidentally?) around the time Google Play was integrated - about four weeks ago.

**Comment by Stephan-P** [comment]
@fckff also after all recommendations made [here](https://discuss.grapheneos.org/d/8330-app-compatibility-with-grapheneos)?

**Comment by fckff** [comment]
@Stephan-P Yes, except for points 4, 6 and 7.

1 Native code debugging was already enabled (it is by default).

2 Enabling exploit protection compatibilty mode has no effect.

3.1 Disabling secure app spawning has no effect.

3.2 Disabling exploit protection compatibilty mode has no effect.

3.3 Restarting has no effect.

3.4 Reverting secure spawning and restarting has no effect.

4 I use Aurora Store and I'm not going to install a sandboxed Google Play Store.

5 Sure.

6 The app doesn't abort at launch.

7 I don't think this is a bug in GOS. 

I have notified ASN Bank through the app, though.

**Comment by fckff** [comment]
>     1. Without the QR-code, the app is practically useless. You can't even use it log in to ASN online banking.
The app is still useful and there are three methods left to login with: password, 'digipass' and 'browsercode'.
>     2. ASN Bank will most likely NOT pick this up
They have before. Yes, this is the second time QR scanning stopped functioning.
>     3. It could be that the sandboxed Playstore would make it functional. Sure you don't want to try?
I'm sure.
> Oh, did you enable camera access for the app?

Yes. That's how I know it worked before ;)

**Comment by Stephan-P** [comment]
@spring-onion 
Recent improvements left a few errors in the Netherlands banking app list.

The "Report" links for tge following Dutch banking apps all point to this single github issue whereas they should lead to independant app issues:

- ASN Bank (is not the app ASN Bank Zakelijk)
- RegioBank (is not the app ASN Bank Zakelijk)
- SNS Bank (is not the app ASN Bank Zakelijk)

**Comment by spring-onion** [comment]
Yup, we're adding those soon.

**Comment by fckff** [comment]
QR code scanning started working again with version 1.19.1, released on June 6.

**Comment by Navia25** [comment]
## ASN Bank Compatibility Report 2026/06/15
### App name
ASN Bank
### Package name
nl.devolksbank.asn.bankieren
### Link to app
https://play.google.com/store/apps/details?id=nl.devolksbank.asn.bankieren
### App version
1.34.2 & 1.35.1
### Version code
131 & 133
### Minimum SDK
API 26
### Target SDK
API 36
### Country of the app
NL
### Build Number
[2026060601](https://grapheneos.org/releases#2026060600)
### Device
- [X] Pixel 6
- [X] Pixel 8
### Receive security preview releases
- [X] Enabled
- [ ] Disabled
### Google Play installed
- [X] Installed
- [ ] Not installed
### Where did you install this app from?
- [ ] Google Play Store
- [X] Aurora Store
- [ ] Accrescent
- [ ] F-Droid Repository
- [ ] Other
### Google Play services Network permission revoked?
- [ ] Revoked
- [X] Not revoked
- [ ] Not installed
### Google Play Integrity API
- [ ] Yes
- [ ] Yes (Blocked)
- [X] No
- [ ] Unknown
### Secure app spawning
- [X] Enabled
- [X] Disabled (Tested)
### Exploit protection compatibility mode
- [X] Enabled (Tested)
- [X] Disabled
### Memory tagging (MTE)
- [X] Enabled (Pixel 8)
- [X] Disabled (Exploit protection compatibility mode)
- [X] Does not apply (Pixel 6)
### Hardened memory allocator
- [X] Enabled
- [X] Disabled (Exploit protection compatibility mode)
### Extended virtual address space
- [X] Enabled (Required by hardened_malloc)
- [ ] Enabled
- [X] Disabled (Exploit protection compatibility mode)
### Native code debugging
- [X] Enabled (Tested)
- [X] Disabled
### WebView JIT
- [X] Disabled
- [ ] Enabled
### Dynamic code loading via memory
- [X] Allowed
- [ ] Restricted
See below for more information.
### Dynamic code loading via storage
- [ ] Allowed
- [X] Restricted
See below for more information.
### Stock OS compatibility
- [ ] Works
- [ ] Does not work
- [X] Unknown
### NFC payments
- [ ] Works
- [ ] Works - but requires another service
- [ ] Does not work
- [X] Not supported
- [ ] Not tested
### App permissions
- [X] Network
- [X] Camera - Allow only while using the app
- [ ] Camera - Ask every time
- [X] Notifications
- [ ] Sensors
### Profile app tested in
- [X] Owner profile
- [ ] Secondary profile(s)
- [ ] Private Space
- [ ] Other
### Description of the app's functionality
Not much to say, the app has resumed to work ever since resolving my past issues, that happened more than a year ago.
Play Integrity enforcement still does not appear to be applicable at all (yay) and hopefully it will stay this way.


### Are there any extra notes you think users should know about?
Dynamic code loading settings were previously untested, I now tested:

1. DCL Memory Allowed / DCL Storage Allowed
Application works.
2. DCL Memory Allowed / DCL Storage Disallowed
Application works.
3. DCL Memory Disallowed / DCL Storage Allowed
Application works, but GrapheneOS does give you the "ASN Bank tried to perform DCL via memory" notification.
4. DCL Memory Disallowed / DCL Storage Disallowed
Application does not work, crashed on opening, and GrapheneOS gives you both the "ASN Bank tried to perform DCL via memory" and "ASN Bank tried to perform DCL via storage" notification.

I am not sure why 2 and 3 both worked (allowing one or the other, and only one gives an attempt notification), cannot reach a conclusion despite having tested with multiple Pixels.

### ADB logcat of the app if necessary
N/A
