### ISSUE TITLE
Digitales Bezahlen

### ISSUE THREAD

**Issue by thilakm-git** [PrivSec-dev/banking-apps-compat-report#160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Digitales Bezahlen

### Link to app

https://play.google.com/store/apps/details?id=de.fiduciagad.android.wlwallet

### App version

21.29.0

### Country of the app

Germany

### Build Number

TP1A.221005.002.2022101200

### Device

- [ ] Pixel 6a
- [ ] Pixel 6 Pro
- [X] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Fully functional.

**Comment by akc3n** [comment]
Thank you.

**Comment by snp42** [comment]
App doesn't work any more on Pixel 6a since last update. Before the last update the app did work without any issues like described above. But since 2023032000 the payment process is interrupted. After re-installing the app no bank card can be added. Tried in main and secondary user profile with Sandboxed Google Play installed.

**Comment by JanWaldhorn** [comment]
> App doesn't work any more on Pixel 6a since last update. Before the last update the app did work without any issues like described above. But since 2023032000 the payment process is interrupted. After re-installing the app no bank card can be added. Tried in main and secondary user profile with Sandboxed Google Play installed.

This is most likely a problem with the app. I installed GrapheneOS about 4 weeks ago and could not add a card. 
Contacting app support revealed that they are having increased issues in the back end due to stronger/new security actions and it is still taking time to resolve the false positives.
Anyway for me it works on a Pixel 6 with the latest stable after following steps:

- Contact the local bank (Sparkasse). In my case, the "Digitalisierung der Karte" was forbidden (unclear why).

- Grant Google Play Services access to the phone (I read it somewhere in [Matrix Chat](https://matrix.to/#/!UVEsOAdphEMYhxzTah:grapheneos.org/$Fkotg7ut9Mr1x4h3ortFQo2N9QMgQETHu2Jnge4Lvds?via=grapheneos.org&via=matrix.org&via=tchncs.de), I think it has to do with Play Integrity API's MEETS_BASIC_INTEGRITY)

- Adding the card do not do it on wifi but with **mobile data**.

Hope that helps

**Comment by snp42** [comment]
Thanks, I was able to add my card again. But curiously I had to use wifi instead of mobile data. In the next days I’m going to check if payment works.

**Comment by snp42** [comment]
Mobile payment does not work with the app at the moment. Tried several times, even with the app open. The app seems to have massive problems, as can also be read in the Play Store reviews. Maybe an upcoming update will solve the problems.

**Comment by JanWaldhorn** [comment]
> Mobile payment does not work with the app at the moment. Tried several times, even with the app open. The app seems to have massive problems, as can also be read in the Play Store reviews. Maybe an upcoming update will solve the problems.

Interesting, I have no problems using it. Did you give Google Play Services access to the phone?

> * Grant Google Play Services access to the phone (I read it somewhere in [Matrix Chat](https://matrix.to/#/!UVEsOAdphEMYhxzTah:grapheneos.org/$Fkotg7ut9Mr1x4h3ortFQo2N9QMgQETHu2Jnge4Lvds?via=grapheneos.org&via=matrix.org&via=tchncs.de), I think it has to do with Play Integrity API's MEETS_BASIC_INTEGRITY)

**Comment by snp42** [comment]
Yes I did. The app worked fine for several months and then about 2 weeks ago, it constantly interrupted the payment process. I then reinstalled but that didn't help.

**Comment by robovoice1** [comment]
https://www.kuketz-blog.de/nfc-datenschutzfreundlich-bezahlen-mit-dem-android-phone/
