### ISSUE TITLE
ING Bankieren - Netherlands

### ISSUE THREAD

**Issue by Sensor66** [PrivSec-dev/banking-apps-compat-report#182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

ING Bankieren

### Link to app

https://play.google.com/store/apps/details?id=com.ing.mobile

### App version

Version: 2022.22.01

### Country of the app

Netherlands

### Build Number

TP1A.221105.002.2022111000

### Device list

Pixel 6a

### Profile app tested in

Owner profile

### Google Play installed

Installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [X] Not enforced
- [ ] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Exploit protection compatibility mode

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Description of the app's functionality

Everything works: checking accounts, making bank transfers, changing banking settings with the bank etc.

**Comment by akc3n** [comment]
Thank you @Sensor66

**Comment by antaljanosbenjamin** [comment]
I have issues enabling fingerprint to verify NFC payments. Sometimes the app asks for verification when I pay with NFC (the app has its own NFC payment implemented, not connected to Google). By default I can verify it by PIN, but the app also provides a toggle to turn on biometric (fingerprint or face id) verification. When I try enable it, it asks for my PIN and then the "loading circle" is shown for quite a while after which I got the following error:
```
Sorry, something went wrong

This is not working properly. Please try again later.
```

It is strange, because I can use my fingerprint in the app to login, but for NFC payment it fails for some reason.

### App version
Version: 2023.12.0.0

### Build Number
TQ3A.230605.012.2023062300

### Device list
Pixel 7

### Profile app tested in
Owner profile

### Google Play installed
Installed

### Google Play services Network permission revoked?
* [ ]  Revoked
* [x]  Not revoked
* [ ]  I did not have Google Play services installed

### SafetyNet Enforcement
* [ ]  Enforced
* [ ]  Not enforced
* [X]  Unsure

### Native code debugging
* [x]  Enabled
* [ ]  Disabled

### Exploit protection compatibility mode
* [X]  Enabled
* [ ]  Disabled

### Stock OS compatibility
* [X]  Works
* [ ]  Does not work
* [ ]  Not tested

### ADB logcat of the app if necessary

_I will add it later._

**Comment by akc3n** [comment]
@antaljanosbenjamin Is this still an ongoing issue? I'll take a closer look at your comment when I get some spare time and reply accordingly.

**Comment by akc3n** [comment]
> @akc3n i found this issue but ING is missing on the website?

Yikes, thank you @ph00lt0 I will update the list.

**Comment by antaljanosbenjamin** [comment]
> @antaljanosbenjamin Is this still an ongoing issue? I'll take a closer look at your comment when I get some spare time and reply accordingly.

It is fixed, but I don't know what fixed it.

**Comment by VolkanGit** [comment]
> > @antaljanosbenjamin Is this still an ongoing issue? I'll take a closer look at your comment when I get some spare time and reply accordingly.
> 
> It is fixed, but I don't know what fixed it.

I hope it really does. I'm honestly contemplating changing to this bank for this :-)

**Comment by antaljanosbenjamin** [comment]
> I hope it really does. I'm honestly contemplating changing to this bank for this :-)

I promise you that I am using ING for a year now and after solving this issue I haven't noticed any issues, except one: I have the feature that hides the sum in my bank account by default and I have to "swipe over the screen" to show. That feature sometimes requires restarting the app, but everything else work like a charm. There is also an alternative way, instead of swiping you can change in the app that double tapping hides/shows the sum. I am not sure if changing for this actually makes sense, but if you end up changing and have issues, I can try to help you.

Probably my issue was orignated from the fact that I changed a lot of settings in OS/for apps, because I was discovering the possibilities and probably messed up something.

**Comment by RonaldPhilipsen** [comment]
Im afraid that ing will stop working soon:

```
Betaal je met je Android™ telefoon wel eens contactloos met je digitale Betaalpas? En doe je dit via onze service ‘ING Mobiel Betalen’, maar nog niet via Google Pay? Dan hebben we een belangrijk bericht voor je.

Vanaf 17 september 2024 kun je ING Mobiel Betalen voor je Android™ telefoon niet meer gebruiken om contactloos af te rekenen in winkels en andere fysieke locaties. Dat kan dan alleen nog via [Google Pay](https://mijn.ing.nl/banking/content/personal/payments-and-creditcards/this-is-how-google-pay-works).

Gebruik je Google Pay nog niet? Stap dan snel en eenvoudig over. Ga daarvoor in je ING-app naar 'Service', vervolgens naar 'Je app-instellingen' en activeer Google Pay in minder dan 2 minuten.
```

**Comment by antaljanosbenjamin** [comment]
> Im afraid that ing will stop working soon:

Yes, but I think there is nothing any of the devs could do. Unfortunately more and more app are transitioning to ApplePay/GPay instead of having their own solution. I think the only workaround is find a phone case that has a card holder :smile:

**Comment by antaljanosbenjamin** [comment]
Aweful that Google doesn't allow to install GPay on graphene os!

**Comment by VolkanGit** [comment]
> Aweful that Google doesn't allow to install GPay on graphene os!

Doesn't it also beat the purpose of using GOS.
don't want to share my data with google or any big tech for that matter.

Companies, banks in this case, should not let themselves get tempted to go for the easy and cheap solution. They are selling out their customers. Like i said earlier, i would change my bank for the sake of privacy.

**Comment by antaljanosbenjamin** [comment]
I think that is the question of what are you willing to "sacrifice" for what. E.g.: I don't want to completely degoogle myself: I still use gmail for example. And I am also would use GPay, if I could install it on GrapheneOS. Would I prefer to use bank provided solutions? Yes, I would love to! However more and more banks decides to go with GPay.

**Comment by Mikey0175** [comment]
From the new version 2025.25.2
com.ing.mobile
versionCode 2024313337
targetSdk 35
minSdk 28

At starting of the app it gives the following error, but still works:
- _You are using a shell runtime library, make sure to process your application with dexguard before releasing_

![Image](https://github.com/user-attachments/assets/8ae6aedd-eb81-486b-bdef-4fb064962a30)

**Comment by HNJAMeindersma** [comment]
I spoke with ING today and they said "the ING Bankieren app still has the same issues as of today since 2022 and that users **will have** issues using the app on Graphene OS".

Reading back this thread it seems the app is/was working with only some smaller issues (besides losing the ability to pay from the app itself to GPay).

Seeing @Mikey0175 post I'm starting to doubt that. Is there any up-to-date information, preferably on the Pixel 10 series? I haven't tried it myself yet since I'd have to buy the hardware first.

**Comment by antaljanosbenjamin** [comment]
> users will have issues using the app on Graphene OS

I am using it without any issues on Pixel 7.
