### ISSUE TITLE
debiX+ - Switzerland

### ISSUE THREAD

**Issue by ghost** [PrivSec-dev/banking-apps-compat-report#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

debiX+

### Link to app

https://play.google.com/store/apps/details?id=com.sixgroup.debixplus

### App version

v1.4.0-prod

### Country of the app

Switzerland 

### Build Number

TQ1A.230205.002.2023030400

### Device list

Pixel 7

### Profile app tested in

Owner profile

### Google Play installed

Installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Exploit protection compatibility mode

- [ ] Enabled
- [ ] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Description of the app's functionality

Managing your bank card.

**Comment by CalvinHub** [comment]
Does not open without Google Play installed. (Version 2.4.0, Pixel 8a, GrapheneOs 2024101200)

**Comment by rmsa5** [comment]
**Setup:**

- Device: Google Pixel 9 Pro
- OS setup: GrapheneOS 2026050700 + GOS Play Service 26.09.31 + GOS Play Store 50.5.19-31 (fresh after Factory Reset on 2026/05/05)
- App version: 3.0.1-prod (google play store) (current as of 2026/05/06)

**Symptoms:**

- DebiX+ app silently crashes/closes immediately after launching.
- App is unusable (no found workaround), making online payment impossible with any of my bank cards (Raiffeisen, Switzerland)

**Steps:**

- Installed app from Play store
- Ran app once with default Exploit protection flags: silent close → I exported app log.
- Next runs do the same.
- Tried clearing storage/cache of app and relaunching: same result
- Uninstall of app + reboot of device
- Reinstallation of app from Play store
- With Exploit protection compatibility mode enabled: close + OS notifies of crash, and provide error output + access to full app log → also exported.
- Tried clearing storage/cache of app and relaunching: same result

**Note:**
Same up-to-date setup (OS, Play Service, DebiX+ app) prior to factory reset that I had been running for over a year, it used to work just fine. I'm betting it is some first-launch-only code in the DebiX+ app that was recently added and is not triggered when updating the already installed app. App Logs attached. Are you able to analyse the logs an explain to me what is going wrong?

**Workaround:**
Called my bank (Raiffeisen, CH), that forwarded me to SixGroup (app maker) phone support, they agreed to toggle SMS authentication instead of DebiX+ app for both my bank cards. Ironically, too much OS security leads to less bank security.

**Comment by exu-g** [comment]
As of today it the app works again for me. Previously I had the same crashing issue  

- Device: Motorola Edge 40 pro
- OS: LineageOS 23.2-20260530-NIGHTLY-rtwo (updated today), microG 0.3.15.250932 (I updated this semi-recently)
- App version: 3.0.1-prod
