### ISSUE TITLE
Openbank – banca móvil

### ISSUE THREAD

**Issue by pachulo** [PrivSec-dev/banking-apps-compat-report#240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Openbank – banca móvil

### Link to app

https://play.google.com/store/apps/details?id=es.openbank.mobile

### App version

1.32.0

### Country of the app

Spain

### Build Number

TQ2A.230305.008.E1.2023032000

### Device list

Pixel 6a

### Profile app tested in

Owner profile

### Google Play installed

Installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Exploit protection compatibility mode

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Description of the app's functionality

Everything works OK, even the "trusted device" feature.

**Comment by Pastitas** [comment]
Is bizum working for you @pachulo

**Comment by pachulo** [comment]
> Is bizum working for you @pachulo

Yes. And also the Mobile Payment option for the cards!

**Comment by Pastitas** [comment]
Any specific steps to get it to work? I've been unable to set it up and no specific error popped up for me

**Comment by pachulo** [comment]
> Any specific steps to get it to work? I've been unable to set it up and no specific error popped up for me

Not really. The only thing is that, before being able to configure a new device as "Dispositivo de confianza", I had to previously desconfigure the old one, because they don't allow you to "overwrite" it.

**Comment by ultraheroe** [comment]
> > Is bizum working for you [@pachulo](https://github.com/pachulo)
> 
> Yes. And also the Mobile Payment option for the cards!

Maybe this feature should be noted in the list.

Want to attach my own report if this helps to do an update, feel free to edit, delete or whatever this comment :)

### Is there an existing issue for this?

- [x] I have searched the existing issues

### App name

Openbank | Banca online

### Link to app

https://play.google.com/store/apps/details?id=es.openbank.mobile

### Country of the app

Spain

### App version

3.1.0

es.openbank.mobile
VersionCode 19137

targetSdk 36
minSdk 26

### Build Number

2026070501

### Device list

Pixel 9a

### Profile app tested in

Owner profile

### Google Play installed?

Installed

### Where did you install this app from?

Google Play Store

### Native code debugging

- [ ] Allowed
- [x] Blocked

### Exploit protection compatibility mode

- [ ] Enabled
- [x] Disabled

### Memory tagging

- [ ] Enabled
- [x] Disabled
- [ ] N/A

### Dynamic code loading via memory

- [ ] Restricted
- [x] Allowed

### Dynamic code loading via storage

- [ ] Restricted
- [x] Allowed

### Does the app use the Play Integrity API?

- [x] Yes *[1]
- [ ] Yes, blocked
- [ ] No

### NFC payments

- [x] Works
- [ ] Works but requires another service
- [ ] Does not work
- [ ] N/A (Not supported by app)
- [ ] Not tested

### Description of the app's functionality

Everything works OK, even the "trusted device" feature.
NFC payment trough the app is working flawlessly, you need to set it as the default payment app

### App requirement

_No response_

### Are there any extra notes you think users should know about?

- *[1] Can't see how to block Play Integrity API on graphene in permissions menu (I think is because it is installed from Google Play and i'm just started to use graphene)
- TBD: attach some pictures to show how to enable a card as default payment method

### ADB logcat of the app if necessary

```systemverilog

```

**Comment by variasdesign** [comment]
Sadly, Openbank is phasing out its own NFC payment model by 15th October, now relying on Google Pay:

> Openbank Pago Móvil dejará de estar disponible
> 
> Hola, Victor:
> 
> Queremos informarte de que el servicio Openbank Pago Móvil para Android dejará de estar disponible el próximo 15 de octubre.
> 
> Hasta esta fecha podrás seguir utilizándolo con normalidad.
> 
> A partir del 15 de octubre:
> 1. Ya no se podrá utilizar Openbank Pago Móvil.
> 2. Las tarjetas que tengas asociadas ya no podrán utilizarse en este servicio.
> 3. No podrás añadir nuevas tarjetas ni gestionar las que ya tengas asociadas.
> 
> Este cambio no afecta al funcionamiento de tus tarjetas Openbank, que podrás seguir utilizando con normalidad para pagar en otras plataformas de pago, como Google Pay o Samsung Pay.
> 
> Sentimos las molestias que te pueda causar. Si tienes cualquier duda, estamos disponibles para ti 24/7.
> 
> Gracias por tu comprensión.
> 
> El equipo de Openbank
