### ISSUE TITLE
Interactive Brokers - Canada

### ISSUE THREAD

**Issue by Arunscape** [PrivSec-dev/banking-apps-compat-report#241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

IBKR Mobile

### Link to app

https://play.google.com/store/apps/details?id=atws.app

### App version

8.4.665

### Country of the app

Canada

### Build Number

TQ2A.230305.008.C1.2023032000

### Device list

Pixel 7 Pro

### Profile app tested in

Owner profile

### Google Play installed

Installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Exploit protection compatibility mode

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Description of the app's functionality

Works great, IBKey (2fa) also works

**Comment by dnerever** [comment]
**Link to app**

https://play.google.com/store/apps/details?id=atws.app
**App version**

8.4.749
**Country of the app**

Canada (Country of use is the United States)
**Build Number**

2024022600

**Device**

- [x] Pixel 8

**Google Play installed**

- [ ] Installed
- [x] Not installed

**Google Play services Network permission revoked?**

- [x] Revoked
- [ ] Not revoked
- [ ] I did not have Google Play services installed

**SafetyNet Enforcement**

- [ ] Enforced
- [ ] Not enforced
- [x] Unsure

**Native code debugging**

    

- [ ] Enabled
- [x] Disabled

**Stock OS compatibility**

    

- [ ] Works
- [ ] Does not work
- [x] Not tested

**Profile app tested in**

- [x] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

**Description of the app's functionality**

Everything seems to work as expected. I did not test any notification functionality.

**Comment by ngrigoriev** [comment]
It appears that when installed without GSF the notifications do not work. This changes the sign-in experience as follows:

- signing in from the desktop app you have to use the challenge/response codes
- signing in from the browser requires to either scan a QR code or switch to the same challenge/response. QR code points to a URL that is locally handled by the IBKR app
- signing in from the mobile app works seamlessly since, I assume, the app receives the challenge as part of its own login sequence
