### ISSUE TITLE
Link to metro bank app is wrong

### ISSUE THREAD

**Issue by ph00lt0** [PrivSec-dev/banking-apps-compat-report#250]
The link to metro bank app on the website points to monzo.

**Comment by the-red-lily** [comment]
I believe this Issue is in the wrong repo:

[Banking Apps Compatibility Reports](https://github.com/PrivSec-dev/banking-apps-compat-report#banking-apps-compatibility-reports)

This repository is for reporting banking app compatibility with GrapheneOS only. If you want to suggest edits on the website, please do so in the [PrivSec-dev/privsec.dev](https://github.com/PrivSec-dev/privsec.dev) repository.

**Comment by the-red-lily** [comment]
Suggest changes here: https://github.com/PrivSec-dev/privsec.dev/blob/main/content/posts/android/Banking%20Applications%20compatibility%20with%20GrapheneOS.md
