### ISSUE TITLE
NFC payments functionality 

### ISSUE THREAD

**Issue by treequell** [PrivSec-dev/banking-apps-compat-report#252]
Enhancement request

Some banks have their own implementation of NFC contactless payments which work on GrapheneOS.

I propose that this is added as an additional field to the banking app report.

**Comment by the-red-lily** [comment]
Popped in a quick PR for this. Open to suggestions

I added the "Works but requires another service" in case Curve (which requires HMS Core for Curve Pay) becomes compatible with GOS or another such case arises

Is there anything to be done for existing app reports? I assume people would have to submit new reports - rather than amending an existing one, am I right?
