### ISSUE TITLE
bank99 ex-ING - Austria

### ISSUE THREAD

**Issue by chaos-prevails** [PrivSec-dev/banking-apps-compat-report#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

bank99 | Online Banking ex-ING

### Link to app

https://play.google.com/store/search?q=bank99+ex+ing&c=apps&hl=en&gl=US

### App version

4.1.1.145

### Country of the app

Austria

### Build Number

TQ3A.230705.001.2023072600

### Device list

Pixel 6a

### Profile app tested in

Owner profile

### Google Play installed

Installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Exploit protection compatibility mode

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Description of the app's functionality

everything works since ~6 month, also push notifications.

**Comment by heinrichat** [comment]
Works for me too. Tested on Pixel 4a, latest stable, main profile, with google play services installed.

**Comment by derkrasseleo** [comment]
Does NFC payment work without gpay?

**Comment by heinrichat** [comment]
> Does NFC payment work without gpay?

I would also like to know that, but I can't because NFC payment is only available for non ex-ING accounts. I called the support hotline. They told me that they want to deprecate the ex-ING app and merge the ex-ING customers to the regular bank99 customers. WIP.

Somebody who has a regular bank99 app (there are two in the play store) could try the NFC feature and report.

BTW you need "Native Code Debugging" enabled for the ex-ING app to work.
