### ISSUE TITLE
Nordea ID

### ISSUE THREAD

**Issue by 0ranki** [PrivSec-dev/banking-apps-compat-report#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Nordea ID

### Link to app

https://play.google.com/store/apps/details?id=com.nordea.mobiletoken

### App version

2.3.1

### Country of the app

Finland

### Build Number

TQ3A.230705.001.2023072600

### Device list

Pixel 7a

### Profile app tested in

Owner profile

### Google Play installed

Not Installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Exploit protection compatibility mode

- [X] Enabled
- [X] Disabled

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### Description of the app's functionality

2FA application for Nordea.

### Are there any extra notes you think users should know about?

Nordea Mobile - Suomi (the actual mobile banking app works too, same settings. With and without Native Code Debugging.

_No response_

**Comment by lbschenkel** [comment]
I was about to add this app and realized it was already added.

A correction: this app is not specific to Finland. It is the same app used in Denmark, Norway, Sweden.  It is confusing since people will search in their country and won't find it in there.

I suggest that it should be duplicated into the 4 countries (better visibility) or at least moved to the international section (not ideal, Nordea is a Nordic but not really an "international" bank and I assume most people will not look there).
