### ISSUE TITLE
CaixaBankNow

### ISSUE THREAD

**Issue by akc3n** [PrivSec-dev/banking-apps-compat-report#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

CaixaBankNow

### Link to app

https://play.google.com/store/apps/details?id=es.lacaixa.mobile.android.newwapicon

### App version

v5.63.0

### Country of the app

Spain

### Build Number

UD1A.231105.004.2023111500

### Device list

Pixel 8 Pro

### Profile app tested in

Secondary profile(s)

### Google Play installed

Not Installed

### Where did you install this app from?

Aurora Store

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### Native code debugging

- [X] Allowed
- [ ] Blocked

### Exploit protection compatibility mode

- [ ] Enabled
- [X] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### NFC payments

- [ ] Works
- [ ] Works but requires another service
- [ ] Does not work
- [ ] N/A (Not supported by app)
- [X] Not tested

### Description of the app's functionality

I haven't found any problems, all the features I use works without problem (including biometric unlocking).

### Are there any extra notes you think users should know about?

The only permissions that the application has are Network and Sensors

---

Submitted report on behalf of a non-github user.

**Comment by Eskuero** [comment]
Installed on a work profile without Sandboxed Play Services. Had to enable DLC via Memory/Storage to prevent crashes.

The app opened, asked to select language and after apparently freezing for a few seconds it claimed that my device "Huawei with HMS" (lol) is no longer compatible.

Installed Play Services without allowing them internet connectivity.

Booted the app again and was able to start the login but didn't test much.

**Comment by tardypad** [comment]
Regrettably the signing functionality is not working anymore since some recent updates.
The app seems to work fine besides this, but without this signing functionality, it's effectively impossible to do any banking operation.

The app is crashing with `Access denied finding property "ro.debuggable"` in the logs.

Related discussion with same issue https://discuss.grapheneos.org/d/26038-caixabank-now-signing/10

Here are my details:
- App version 5.85.1
- Pixel 8
- Installed on secondary profile
- Installed from Google Play Store
- Has Google Play Services enabled (Network permission is allowed)
- Has Exploit protection compatibility mode enabled (Native code debugging allowed).
  Everything used to be working with it being disabled, but I've tried this mode to see if it would get rid of the crash.

I will report this issue to the bank, and will update in case I get a reply.

**Comment by tardypad** [comment]
Did a few more testing and I've managed to have the signing working again now (hopefully this will last🤞)

I've reinstalled the app, logged out and in again,... and such. But what I think was important was installing the "Google Play Store" app in that secondary profile (I'm not even logged in in there). I previously only had the "Google Play Services" installed in that profile. I figured this out after seeing that the functionality was working fine when testing in my Owner profile (where I have all the store apps installed)

And to confirm: it also works with the default exploit protection as before.

**Comment by primijos** [comment]
For anyone that might be interested: I've faced a similar issue with the Caixabank app in GrapheneOS. At first, I thought it was related to the use of GrapheneOS (hardened malloc etc.) but it turns out it was related to the use of a VPN.

When using a VPN (Mullvad), the app complained about Internet connectivity (an error message stating there was no network connection appeared), and the "ro.debuggable" message also appeared in the logs. However, when I disable the VPN, the application works perfectly. Only, from time to time, a notification appears stating that Google Play Services (don't remember exactly) requires telephone permission for the app (Caixabank) to work correctly. I haven't granted that permision but the app still works fine if I disable the VPN.

This is probably due to some provider/firewall blocking Mullvad for whatever reason (I've find that, for example, reddit blocks also browsing when I access to it via Mullvad VPN, and CloudFlare activates security checks a lot more frequently when I access to some services via Mullvad VPN as opposed to when I don't use VPN)

Just in case this helps you
