### ISSUE TITLE
Ubank Money App

### ISSUE THREAD

**Issue by SimonBrazell** [PrivSec-dev/banking-apps-compat-report#469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Ubank Money App

### Link to app

https://play.google.com/store/apps/details?id=au.com.bank86400&hl=en_AU&pli=1

### App version

11.32.0

### Country of the app

Australia

### Build Number

1014062000

### Device list

Pixel 7

### Profile app tested in

Owner profile

### Google Play installed?

Installed

### Where did you install this app from?

Google Play Store

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### Native code debugging

- [X] Allowed
- [X] Blocked

### Exploit protection compatibility mode

- [X] Enabled
- [X] Disabled

### Memory tagging extension (MTE)

- [ ] Enabled
- [ ] Disabled
- [X] N/A

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### NFC payments

- [ ] Works
- [ ] Works but requires another service
- [ ] Does not work
- [ ] N/A (Not supported by app)
- [X] Not tested

### Description of the app's functionality

When attempting to sign-up for an account via the app (which is the only way to sign up it seems) you are prompted to create a passkey to continue, this step fails and there is no other way to continue, meaning it is completely unusable.

**Comment by FID02** [comment]
@SimonBrazell Hello. Community member here. 

I would like to determine whether the app is trying to save a _passkey_ or simply prompting the user to create a _passcode_. It will make further troubleshooting easier if we can clarify this. 

I'm asking because I can see that the app will prompt the user to create a _passcode_ during the setup process (see attached screenshot), but the setup menu doesn't mention passkeys. But since I'm not an Australian citizen, I cannot complete the setup wizard to verify this. 

Could you please take screenshots of the dialogs/screens that are displayed both before and when the error occurs, and upload them here? The app blocks screenshotting from the quick-switch menu, but you can press power + volume down simultaneously to take one, which is not blocked.

![Screenshot_20240629-142108.png](https://github.com/PrivSec-dev/banking-apps-compat-report/assets/99329251/ae7818d9-e8f7-478b-9fd1-41c372477239)

**Comment by SimonBrazell** [comment]
Hello @FID02 thanks for responding 🙂

So the following steps are mandatory for either sign up or if you attempt to sign in after having signed up on another device:

1. ![1](https://github.com/PrivSec-dev/banking-apps-compat-report/assets/16571951/8ce267f6-20d9-403d-bfed-0a49b88a12d9)

2. ![2](https://github.com/PrivSec-dev/banking-apps-compat-report/assets/16571951/7ab5d693-ea11-4c85-b99e-19c21ddcfadf)

3. ![3](https://github.com/PrivSec-dev/banking-apps-compat-report/assets/16571951/cf338570-1be6-436a-9b97-43600b37be44)

When you click continue on the second step the error modal comes up after a short time.

**Comment by FID02** [comment]
@SimonBrazell Good. That means the issue is probably fixable by either a) getting Google Password Manager to work correctly; or b) setting up a third-party password manager with passkey support. 

You could normally choose to use a physical security key, but it sounds to me as though the app chooses not to allow that (it does not call the Play Services dialog "No passkeys available" with more options, but instead throws an error).

I'll explain the two alternatives in turn. 

Alternative B might be the most popular way of using passkeys on GrapheneOS (if one is to judge by how frequently it's brought up in the community), but it's up to you what to use. Google Password Manager might be tricky to set up because of OS restrictions set by Google.

# A) Google Password Manager

To test if your Google account is eligible for saving passkeys in Google Password Manager: 

Go to https://passkey.org and scroll down to "Try it out". 

Enter anything in the username field and select "sign up".

Select "Continue" in the passkey popup dialog

If you then get a new window from Google where you are asked to enter the unlock PIN/password of one your previous or current devices, do that, then proceed to save the passkey from passkey.org. You can then restart Ubank and try the app again. 

If you don't get the passkey popup dialog, or if a window is presented telling you that "Your encrypted data is locked on this device", it's probably easier to just proceed to alternative B. If you still want to use your Google account for passkeys on GrapheneOS, you need the following:

A second device with a stock Android OS – for instance a Samsung phone without a user-installed alternate OS (could be your own or for instance a friend's device)

Having your Google account signed in as a system account, in any user profile, on the second device

Then do this: 

On the second device, create a new user profile. Since menus vary across Android variants, I can't tell you specific steps on how to do this, but you can normally go to the Settings app and do a search for 'profile'.

In the setup wizard for the new user profile, sign in to your Google account and set up an unlock PIN (no need to enable data collection, device backup, etc.) 

Do the passkey.org procedure again

On your GrapheneOS device, do the passkey.org procedure again. This time you should be asked for the unlock PIN of the other device.

Then try the Ubank app again.

# B) A third-party password manager of your choice

Any password manager that supports passkeys on Android should do. The most popular among the GrapheneOS community seems to be Bitwarden and Proton Pass. But it's up to you, and an online search will give you further options. (Note: 1Password blocks using passkeys in Vanadium).

When you have signed up for an account with a password manager (preferably using a strong, unique master password, but that's optional), and installed and set up their app, do this:

Go to the Settings app > Passwords, passkeys & autofill > Cogwheel > Select your password manager.

Open Vanadium and go to Settings > Autofill Options > Select "Use other providers".

Then restart Ubank and try again.

If that doesn't work, reboot your phone and try again.

If your default browser is not Vanadium, please consult your password manager's documentation for how to set it up for the browser. I'm assuming here that Ubank is using the default browser to call the passkey dialog, but I could be wrong.

**Comment by SimonBrazell** [comment]
@spring-onion thanks heaps for the instructions, sorry I didn't get back to this earlier.

So I tried with Google Password manager using another device and with Bitwarden, both no luck, although I got a little further with Bitwarden. With it I can create and store the passkey but then when I attempt to use it to login the app just gets stuck on an endless `Logging in...` screen, I had a quick look at the application logs and it shows the following error message:

```
07-09 04:50:39.661 32252 32353 E chromium: [ERROR:cookie_manager.cc(135)] Strict Secure Cookie policy does not allow setting a secure cookie for http://ubank.com.au/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.
07-09 04:50:39.662 32252   455 E BMP:PoW : Failed to get PoW Params, HTTP response code: 403
07-09 04:50:39.663 32252   455 E BMP:PoW : Error: Get Params error
```

Which indicates to me that the application is attempting to use the `Secure` attribute on a cookie when using HTTP... pretty dodgy, I wonder if there is a way to bypass this protection for the time being? Or I guess I could report this to the developers.

**Comment by SimonBrazell** [comment]
Actually just tried again with Google Password Manager and it seems to fail at the same point.

**Comment by FID02** [comment]
> I had a quick look at the application logs and it shows the following error message:
> 
> ```
> 07-09 04:50:39.661 32252 32353 E chromium: [ERROR:cookie_manager.cc(135)] Strict Secure Cookie policy does not allow setting a secure cookie for http://ubank.com.au/ for apps targeting >= R. Please either use the 'https:' scheme for this URL or omit the 'Secure' directive in the cookie value.
> 07-09 04:50:39.662 32252   455 E BMP:PoW : Failed to get PoW Params, HTTP response code: 403
> 07-09 04:50:39.663 32252   455 E BMP:PoW : Error: Get Params error
> ```
> 
> Which indicates to me that the application is attempting to use the `Secure` attribute on a cookie when using HTTP... pretty dodgy, I wonder if there is a way to bypass this protection for the time being? Or I guess I could report this to the developers.
> 
@SimonBrazell 

Judging from the error message, I don't think there's much more you can do. I don't have the technical insight into Chromium security, but I suspect there are good reasons for Vanadium to set that Strict Secure Cookie Policy. It sounds like something the banking app developers should take a look at.

Since you managed to store the passkey in Bitwarden, that indicates to me that the passkey functionality works as it should and that there's no issue on that front. 

I think opening a support ticket with the bank would be the next step here.

**Comment by SimonBrazell** [comment]
Yeah thanks @FID02 I thought as much, I decided to not bother with this bank, the app seems poorly maintained, found another that meets my needs and works on GOS. 

Do you want me to close this ticket?

**Comment by SimonBrazell** [comment]
It's been a valuable exercise still as I setup Bitwarden and got my head around the passkey feature 🙂

**Comment by spring-onion** [comment]
Just noticed there's an older report [here](https://github.com/PrivSec-dev/banking-apps-compat-report/issues/156), please continue conversation there. I'll reference you lot's findings.
