### ISSUE TITLE
OP-mobiili Finland

### ISSUE THREAD

**Issue by tarikki** [PrivSec-dev/banking-apps-compat-report#479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

OP-mobiili

### Link to app

https://play.google.com/store/apps/details?id=fi.op.android.opmobiili&hl=fi&pli=1

### App version

66.0.1

### Country of the app

Finland

### Build Number

2024072800

### Device list

Pixel 8

### Profile app tested in

Owner profile

### Google Play installed?

Installed

### Where did you install this app from?

Google Play Store

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### Native code debugging

- [X] Allowed
- [ ] Blocked

### Exploit protection compatibility mode

- [ ] Enabled
- [X] Disabled

### Memory tagging extension (MTE)

- [ ] Enabled
- [X] Disabled
- [ ] N/A

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [ ] Not tested

### NFC payments

- [ ] Works
- [ ] Works but requires another service
- [ ] Does not work
- [X] N/A (Not supported by app)
- [ ] Not tested

### Description of the app's functionality

Works perfectly for both banking and identification services.

### Are there any extra notes you think users should know about?

The app will ask for you to give google play the SMS and calls permissions.

**Comment by spring-onion** [comment]
Appreciate all the reports!

**Comment by onni-2** [comment]
Without Play Services installed, OP-mobiili displays a warning on every launch:
"Device not compatible. OP-mobiili can't run because your device doesn't support Google Play services. Please use a supported device."

However, the **app works perfectly fine** after closing the popup with "OK". 
Tested on Pixel 9a and 7a on build 2026070500, app version 84.0.0.

It is worth noting that in a Google Play Store review (04/2026) referring to GrapheneOS, the developer has stated as follows: "We can only guarantee the reliable and secure operation of the application on officially released Android versions."
