### ISSUE TITLE
UBS TWINT

### ISSUE THREAD

**Issue by suchprototype** [PrivSec-dev/banking-apps-compat-report#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

UBS TWINT

### Link to app

https://play.google.com/store/apps/details/UBS_TWINT?id=com.ubs.Paymit.android

### App version

42.2.0.158

### Country of the app

Switzerland

### Build Number

2024091900

### Device list

Pixel 8 Pro

### Profile app tested in

Owner profile

### Google Play installed?

Not Installed

### Where did you install this app from?

Aurora Store

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### Native code debugging

- [ ] Allowed
- [X] Blocked

### Exploit protection compatibility mode

- [ ] Enabled
- [X] Disabled

### Memory tagging extension (MTE)

- [X] Enabled
- [ ] Disabled
- [ ] N/A

### Dynamic code loading via memory

- [X] Restricted
- [ ] Allowed

### Dynamic code loading via storage

- [X] Restricted
- [ ] Allowed

### Stock OS compatibility

- [X] Works
- [ ] Does not work
- [X] Not tested

### NFC payments

- [ ] Works
- [ ] Works but requires another service
- [ ] Does not work
- [X] N/A (Not supported by app)
- [ ] Not tested

### Description of the app's functionality

@spring-onion: **Now requires Google Play.**

Everything works. TWINT doesn't use NFC to do payments. You just need to scan a QR code to pay and it works great :)

https://www.ubs.com/ch/en/private/digital-banking/apps/twint.html

https://www.twint.ch/en/bank/ubs/

**Comment by spring-onion** [comment]
Great, thanks for all the reports!

**Comment by nicdumz** [comment]
@suchprototype on Twint v42.3.0.13 on a Pixel 8 I currently get UI flickers leading to crashes. Do you still have a stable UBS Twint?

I didn't really manage to get it stabilized.

Error logs reveal things like `E chromium: [ERROR:aw_browser_terminator.cc(165)] Renderer process (12906) crash detected (code -1).`

Attaching a W+ set of logs

[TWINT log _ W+ 2d6c5251710f.txt](https://github.com/user-attachments/files/17981350/TWINT.log._.W%2B.2d6c5251710f.txt)

**Comment by Mo0-n** [comment]
I came here to report the same @nicdumz . @suchprototype does it still works for you?

Twint v42.3.0.13, tried on separate profile without play service. Installed with google play on owner profile.
Pixel 8 Pro

I have also flickering; the app eventually crashes. It happened only after attempting to transfer money (which didn't work - it worked with my former phone with stock OS just after) first time, then any subscequent use of the app had flickering. UBS banking app with access app works seamlessly.

New GrapheneOS user, i tried only to activate exploit compatibility mode, doesn't solve the issue. 

After this, I tried on owner profile, where I have play services and orbot Tor VPN. Stopped the VPN (otherwise the twint app says "no connection", force stopped play store and play service, initialized access and twint and I could transfer money, no flickering. 

But the point is that I don't want to use my Twint app in the owner profile, so it does not solve the issue for my use case.

**Comment by spring-onion** [comment]
@nicdumz @Mo0-n It's not super unusual for a banking app to expect and/or need google play services.

I would like to know if it's okay with being in a secondary profile. Install google play there and let me know please. It's very rare for an app to refuse to work in anything but the owner profile, but it can happen.

**Comment by nicdumz** [comment]
Yes, you're right, it works fine in a (non-owner) profile with GPS installed.

Hardening+Memory tagging is fine. Blocking native code debugging is possible. 

The app does try DCL via storage but works fine (?) if GOS restricts it. I might not have discovered the feature depending on Dynamic code loading.

**Comment by spring-onion** [comment]
Alright thanks for the info. Users who prefer to not run google play in their main profile can segregate it then.

**Comment by Mo0-n** [comment]
Thank you. I also confirm UBS Twint works in separate profile (not owner) with google play services (tested: parking fees & send money).
