### ISSUE TITLE
BW Mobilbanking Phone + Tablet

### ISSUE THREAD

**Issue by boringthings** [PrivSec-dev/banking-apps-compat-report#523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

BW Mobilbanking Phone + Tablet

### Link to app

https://play.google.com/store/apps/details?id=com.starfinanz.smob.android.bwmobilbanking

### App version

6.7.5

### Country of the app

Germany

### Build Number

2024102400

### Device list

Pixel 6a

### Profile app tested in

Secondary profile(s)

### Google Play installed?

Not Installed

### Where did you install this app from?

Aurora Store

### Google Play services Network permission revoked?

- [ ] Revoked
- [ ] Not revoked
- [X] I did not have Google Play services installed

### Native code debugging

- [X] Allowed
- [ ] Blocked

### Exploit protection compatibility mode

- [ ] Enabled
- [X] Disabled

### Memory tagging extension (MTE)

- [ ] Enabled
- [ ] Disabled
- [X] N/A

### Dynamic code loading via memory

- [ ] Restricted
- [X] Allowed

### Dynamic code loading via storage

- [ ] Restricted
- [X] Allowed

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### NFC payments

- [ ] Works
- [ ] Works but requires another service
- [ ] Does not work
- [X] N/A (Not supported by app)
- [ ] Not tested

### Description of the app's functionality

App works as expected.

### Are there any extra notes you think users should know about?

- App needs enabled native code debugging to start.
- Additionally a token generator like app "BW pushTAN" is needed for task authorization
- App integrates with KeepassDX password manager. Direct form fill as well as Magic Keyboard are supported.

**Comment by spring-onion** [comment]
Thanks!

**Comment by arthurghwindsor** [comment]
I'd like to suggest an update to this report and potentially #44 . Since an update couple of months ago if the user has "Memory Tagging" enabled, the app would consistently often (not all the time) loop back to the login page when the user tries to login to/access the app. Having "Memory Tagging" disabled solves this. I don't know if this also happens in the normal Sparkasse app with the issue #44 but most probably yes because they essentially have the exact same code, just that the BW-Bank app has the BIC number locked to of course BW-Bank.
