### ISSUE TITLE
Virgin Money Mobile Banking

### ISSUE THREAD

**Issue by davearchive** [PrivSec-dev/banking-apps-compat-report#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Virgin Money Mobile Banking

### Link to app

https://play.google.com/store/apps/details?id=com.virginmoney.uk.mobile.android

### App version

22.3.253

### Country of the app

United Kingdom 

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [X] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [ ] Main user profile
- [X] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

App works perfectly

**Comment by epagone** [comment]
I hope this is the right place to raise that the app does **not** work for me (please direct me otherwise).

I am on Pixel 8 Pro and dealing with the Virgin Money Mobile App version 23.11.276. All other settings and specs are exactly as in the original message of this issue. However, when I try to register my device and I specify either the username or the customer number, I'm getting a generic error "Oops Something's gone wrong" followed by a 6-digit hex "error ID" that is different every time.

I have tried entering
- my username
- my customer number
- the whole set of personal details (name, surname, address post code, etc...)

always obtaining the above result.

Once (over ten-ish attempts) very strangely my username has been accepted and the generic error above appeared after I entered my password. I have the app working perfectly on a Android 8.1 device for the same account.

Any suggestions, please?

**Comment by davearchive** [comment]
Hi mate

You will have to phone virgin as they have some issues registering the app. But I have checked and it still works fine in graphene.

**Comment by davearchive** [comment]
Ah glad you got it working. I did find that I had to call Virgin to get the app installed even on a Chromebook.
